document.addEventListener("DOMContentLoaded",()=>{
 const select=document.getElementById("bookingCar"),form=document.getElementById("bookingForm"),summary=document.getElementById("bookingSummary");
 cars.forEach(c=>select.add(new Option(`${c.name} — ₹${c.price.toLocaleString()}/day`,c.id)));
 const params=new URLSearchParams(location.search); if(params.get("car"))select.value=params.get("car");
 const today=new Date().toISOString().split("T")[0];document.getElementById("pickupDate").min=today;document.getElementById("returnDate").min=today;
 [select,document.getElementById("pickupDate"),document.getElementById("returnDate")].forEach(x=>x.addEventListener("input",updateSummary));updateSummary();
 form.addEventListener("submit",e=>{e.preventDefault();const data=new FormData(form),pickup=new Date(data.get("pickup")),ret=new Date(data.get("return"));if(ret<=pickup){showMsg("Return date must be after the pickup date.",true);return}const car=cars.find(c=>c.id===Number(data.get("carId")));const days=Math.ceil((ret-pickup)/86400000);const booking={id:"DE-"+Date.now().toString().slice(-7),name:data.get("name"),email:data.get("email"),phone:data.get("phone"),license:data.get("license"),carId:car.id,carName:car.name,pickup:data.get("pickup"),return:data.get("return"),location:data.get("location"),note:data.get("note"),days,total:days*car.price,created:new Date().toISOString()};const list=JSON.parse(localStorage.getItem("driveease-bookings")||"[]");list.unshift(booking);localStorage.setItem("driveease-bookings",JSON.stringify(list));form.reset();select.value=car.id;showMsg(`Booking ${booking.id} confirmed! Your total is ₹${booking.total.toLocaleString()}.`);updateSummary();});
 function showMsg(m,err){const el=document.getElementById("bookingMessage");el.textContent=m;el.style.color=err?"#b33":"#2b7b49"}
 function updateSummary(){const car=cars.find(c=>c.id===Number(select.value))||cars[0];const p=document.getElementById("pickupDate").value,r=document.getElementById("returnDate").value;let days=1;if(p&&r){const diff=(new Date(r)-new Date(p))/86400000;days=diff>0?diff:1}summary.innerHTML=`<span class="eyebrow">YOUR SELECTION</span><img src="${car.image}" alt="${car.name}"><h2>${car.name}</h2><p>${car.category} · ${car.fuel} · ${car.seats} seats</p><div class="summary-price">₹${(car.price*days).toLocaleString()}</div><p>Estimated rental for <strong>${days} day${days!==1?"s":""}</strong></p><div class="summary-line"><span>Daily rate</span><strong>₹${car.price.toLocaleString()}</strong></div><div class="summary-line"><span>Rental days</span><strong>${days}</strong></div><div class="summary-line"><span>Total</span><strong>₹${(car.price*days).toLocaleString()}</strong></div>`}
});